@echo off

: net stop    "Application Experience"
: net stop    "Application Information"
: net stop    "Base Filtering Engine"
: net stop    "Certificate Propagation"
: net stop    "COM+ Event System"
: net stop    "Cryptographic Services"
: net stop    "DCOM Server Process Launcher"
: net stop    "Desktop Window Manager Session Manager"
: net stop    "DHCP Client"
net stop    "Diagnostic Policy Service"
net stop    "Diagnostic Service Host"
net stop    "Diagnostic System Host"
net stop    "Distributed Link Tracking Client"
: net stop    "DNS Client"
net stop    "Group Policy Client"
: net stop    "Hyper-V Data Exchange Service"
: net stop    "Hyper-V Guest Shutdown Service"
: net stop    "Hyper-V Heartbeat Service"
: net stop    "Hyper-V Time Synchronization Service"
: net stop    "Hyper-V Volume Shadow Copy Requestor"
: net stop    "IP Helper"
net stop    "Microsoft Office Click-to-Run Service"
: net stop    "Multimedia Class Scheduler"
: net stop    "Network Connections"
net stop    "Network List Service"
: net stop    "Network Location Awareness"
net stop    "Network Store Interface Service"
: net stop    "Office Software Protection Platform"
net stop    "Offline Files"
: net stop    "Plug and Play"
: net stop    "Power"
: net stop    "Print Spooler"
: net stop    "Program Compatibility Assistant Service"
net stop    "Remote Desktop Configuration"
net stop    "Remote Desktop Services"
net stop    "Remote Desktop Services UserMode Port Redirector"
: net stop    "Remote Procedure Call (RPC)"
: net stop    "RPC Endpoint Mapper"
: net stop    "Security Accounts Manager"
: net stop    "Security Center"
: net stop    "Server"
: net stop    "Shell Hardware Detection"
: net stop    "Software Protection"
net stop    "SQL Server VSS Writer"
net stop    "Superfetch"
: net stop    "System Event Notification Service"
: net stop    "Task Scheduler"
net stop    "TCP/IP NetBIOS Helper"
: net stop    "Themes"
: net stop    "User Profile Service"
: net stop    "VirtualBox Guest Additions Service"
: net stop    "Windows Audio"
: net stop    "Windows Audio Endpoint Builder"
net stop    "Windows Defender"
: net stop    "Windows Event Log"
net stop    "Windows Firewall"
: net stop    "Windows Font Cache Service"
: net stop    "Windows Image Acquisition (WIA)"
: net stop    "Windows Licensing Monitoring Service"
: net stop    "Windows Management Instrumentation"
net stop    "Windows Phone IP over USB Transport (IpOverUsbSvc)"
net stop    "Windows Search"
net stop    "Windows Update"
: net stop    "Workstation"

